name: Relatório de bug (CodeChat)
description: Crie um relatório para nos ajudar a melhorar.
labels:
  - bug
  - help wanted
  - pt-br
assignees: jrcleber
body:
  - type: markdown
    attributes:
      value: '## Bem-vindo!'

  - type: markdown
    attributes:
      value: |
        O rastreador de problemas é apenas para relatar bugs e solicitações de recursos.
        Para perguntas de suporte relacionadas ao usuário final, acesse o [Grupo](https://chat.whatsapp.com/HyO8X8K0bAo0bfaeW8bhY5).

        **NÃO ABRA UM PROBLEMA PARA PERGUNTAS GERAIS DE SUPORTE.**

  - type: markdown
    attributes:
      value: |
        Como escrever um bom relatório de bug?

        - Respeite o modelo de problema tanto quanto possível.
        - O título deve ser curto e descritivo.
        - Explique as condições que o levaram a reportar este problema: o contexto.
        - O contexto deve levar a algo, ideia ou problema que você está enfrentando.
        - Seja claro e conciso.
        - Formate suas mensagens para ajudar o leitor a se concentrar no que importa e entender a estrutura da sua mensagem, use [sintaxe Markdown](https://help.github.com/articles/github-flavored-markdown)

        ---

  - type: checkboxes
    id: terms
    attributes:
      label: Pesquisei problemas semelhantes no [GitHub](https://github.com/code-chat-br/whatsapp-api/issues) e não encontrei nenhum.
      description: Pesquise tanto nas issue abertas quanto nas fechadas.
      options:
        - label: Sim
          required: true

  - type: markdown
    attributes:
      value: '### O que você fez?'
  - type: textarea
    attributes:
      label: 'Quais passos para chegar ao problema?'
      placeholder: Descreva
    validations:
      required: true

  - type: markdown
    attributes:
      value: '### O que você esperava?'
  - type: textarea
    attributes:
      label: Descreva o que você esperava que acontecesse.
      placeholder: O que você esperava?
    validations:
      required: true

  - type: markdown
    attributes:
      value: '### O que vc observou ao invés do que esperava?'
  - type: textarea
    attributes:
      label: Explique o que realmente acontece quando você segue os passos acima.
      placeholder: O que vc observou ao invés do que esperava?
    validations:
      required: true

  - type: markdown
    attributes:
      value: '### Qual versão da API você está usando?'
  - type: textarea
    attributes:
      label: Insira o número da sua versão que está na propriedade `version` do **package.json**.
      placeholder: Cole aqui a versão.
    validations:
      required: true

  - type: markdown
    attributes:
      value: '### Capturas de Tela/Vídeos'
  - type: textarea
    attributes:
      label: |
        Se possível, adicione capturas de tela ou vídeos que ilustrem o problema.
        Isso pode ser extremamente útil para entender melhor o problema.
      placeholder: mídioas que ajudam a identificar o problema

  - type: markdown
    attributes:
      value: '### Qual é o seu ambiente?'
  - type: dropdown
    id: select
    attributes:
      label: O ambiente no qual a aplicação está em execução
      options:
        - Windows
        - Linux
        - Mac
        - Docker
        - Outro
    validations:
      required: true

  - type: markdown
    attributes:
      value: '### Se aplicável, cole a saída do log'
  - type: textarea
    attributes:
      label: |
        Por favor, anexe os logs que possam estar relacionados ao problema.
        Se os logs contiverem informações sensíveis, considere enviá-los de forma privada para um dos mantenedores do projeto.
      placeholder: Cole aqui o log da aplicação
    validations:
      required: false

  - type: markdown
    attributes:
      value: '### Notas Adicionais'
  - type: textarea
    attributes:
      label: Inclua aqui qualquer outra informação que você ache que possa ser útil para entender ou resolver o bug.
    validations:
      required: false
