name: Solicitação de recursos (CodeChat)
description: Sugira ideias para o projeto.
assignees: jrcleber
labels:
  - enhancement
  - pt-br
body:
  - type: markdown
    attributes:
      value: '## Bem-vindo!'

  - type: markdown
    attributes:
      value: |
        O rastreador de problemas é apenas para relatar bugs e solicitações de recursos.
        Para perguntas de suporte relacionadas ao usuário final, acesse o [Grupo](https://chat.whatsapp.com/HyO8X8K0bAo0bfaeW8bhY5).

        **NÃO ABRA UM PROBLEMA PARA PERGUNTAS GERAIS DE SUPORTE.**
        
  - type: markdown
    attributes:
      value: |
        Como escrever um bom relatório de bug?

        - Respeite o modelo de problema tanto quanto possível.
        - O título deve ser curto e descritivo.
        - Explique as condições que o levaram a reportar este problema: o contexto.
        - O contexto deve levar a algo, ideia ou problema que você está enfrentando.
        - Seja claro e conciso.
        - Formate suas mensagens para ajudar o leitor a se concentrar no que importa e entender a estrutura da sua mensagem, use [sintaxe Markdown](https://help.github.com/articles/github-flavored-markdown)

        ---

  - type: checkboxes
    id: terms
    attributes:
      label: Pesquisei problemas semelhantes no Github e não encontrei nenhum.
      description: Pesquise tanto nas [issue abertas quanto nas fechadas](https://github.com/code-chat-br/whatsapp-api/issues).
      options:
        - label: Sim
          required: true

  - type: markdown
    attributes:
      value: '### Qual tipo de recurso?'
  - type: dropdown
    attributes:
      label: 'Recurso de:'
      options:
        - Integração
        - Funcionalidade
        - Endpoint
        - Ajuste de banco de dados
        - Outro
    validations:
      required: true

  - type: markdown
    attributes:
      value: '### Qual a motivação para a solicitação?'
  - type: textarea
    attributes:
      label: Qual problema o recurso busca resolver?
      placeholder: Descreva a motivação para o recurso
    validations:
      required: true

  - type: markdown
    attributes:
      value: '###  Exemplos de Uso'
  - type: textarea
    attributes:
      label: |
        Forneça exemplos específicos de como essa funcionalidade poderia ser utilizada.
        Isso pode incluir cenários ou casos de uso onde a funcionalidade seria particularmente benéfica.
      placeholder: texto - imagem - video - fluxogramas
    validations:
      required: false

  - type: markdown
    attributes:
      value: '### Como o recurso deve ser desenvolvido?'
  - type: textarea
    attributes:
      label: Desenvolvimento
      description: |
        Deve ser inserido diretamente no código?
        Deve ser construído uma aplicação diferente que atuará como uma extenção da api? 
        Por exemplo: um `worker`?
        
        Discuta como essa nova funcionalidade poderia impactar outras partes do projeto, se aplicável.

        ---

        Se você tem ideias sobre como essa funcionalidade pode ser implementada, por favor, compartilhe-as aqui.
        Isso não é obrigatório, mas pode ser útil para a equipe de desenvolvimento.

      placeholder: Insira ideias para o recurso
    validations:
      required: false

  - type: markdown
    attributes:
      value: '### Pode ser construído com o n8n?'
  - type: textarea
    attributes:
      label: n8n
      description: |
        Quais nós podem ser usados?
        Descreva o fluxo.
      placeholder: Descreva o workflow
    validations:
      required: false

  - type: markdown
    attributes:
      value: '### Notas Adicionais'
  - type: textarea
    attributes:
      label: Qualquer outra informação que você acredita ser relevante para a sua solicitação.
      placeholder: Insira aqui as sua observções.
    validations:
      required: false
